// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDrsv80pfgC-eEZr60ZWngeQPbdnR-p1I',
    appId: '1:505537525642:web:9d216881c61c300698fa73',
    messagingSenderId: '505537525642',
    projectId: 'taninowine-app',
    authDomain: 'taninowine-app.firebaseapp.com',
    storageBucket: 'taninowine-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkPUa7fjKVGnLPOF--cLavfXRVY3X0F3Y',
    appId: '1:505537525642:android:79b70ecb40505d4098fa73',
    messagingSenderId: '505537525642',
    projectId: 'taninowine-app',
    storageBucket: 'taninowine-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaWidz61En4xN6kJZUGMXSXUZMOmMFXUs',
    appId: '1:505537525642:ios:6458b9254f5cdb4498fa73',
    messagingSenderId: '505537525642',
    projectId: 'taninowine-app',
    storageBucket: 'taninowine-app.firebasestorage.app',
    iosBundleId: 'com.example.taninowine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaWidz61En4xN6kJZUGMXSXUZMOmMFXUs',
    appId: '1:505537525642:ios:6458b9254f5cdb4498fa73',
    messagingSenderId: '505537525642',
    projectId: 'taninowine-app',
    storageBucket: 'taninowine-app.firebasestorage.app',
    iosBundleId: 'com.example.taninowine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDrsv80pfgC-eEZr60ZWngeQPbdnR-p1I',
    appId: '1:505537525642:web:c8fa0abf6b25596098fa73',
    messagingSenderId: '505537525642',
    projectId: 'taninowine-app',
    authDomain: 'taninowine-app.firebaseapp.com',
    storageBucket: 'taninowine-app.firebasestorage.app',
  );
}
